### ISSUE TITLE
App breaks when adjusting the channel order

### ISSUE THREAD

**Issue by Monstanner** [mediathekview/zapp#371]
As described in the title. If you change the channel order, the app breaks and can no longer be opened.

Here is the crash report:

```
REPORT_ID=c850e8d4-dd43-42a1-9232-8d4a07bef03a
USER_EMAIL=
USER_COMMENT=
IS_SILENT=false
USER_CRASH_DATE=2023-07-20T17:12:04.879+02:00
APP_VERSION_NAME=8.3.0
APP_VERSION_CODE=66
ANDROID_VERSION=10
PHONE_MODEL=Nokia 6.1
BRAND=Nokia
SHARED_PREFERENCES=default.pref_key_start_tab=live
	default.pref_key_player_zoomed=false
	default.pref_ui_mode=default
	default.dynamic_colors=false
	default.pref_detail_landscape=true
	default.pref_key_pip_on_back=false
	default.pref_key_language=de
	default.pref_download_wifi_only=true
	default.pref_shortcuts=[]
	default.pref_key_download_to_sd_card=true
	default.pref_key_stream_quality_cellular=disabled
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{de.christinecoenen.code.zapp/de.christinecoenen.code.zapp.app.main.MainActivity}: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(activitythread.java:3271)
	at android.app.ActivityThread.handleLaunchActivity(activitythread.java:3410)
	at android.app.servertransaction.LaunchActivityItem.execute(launchactivityitem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(transactionexecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(transactionexecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(activitythread.java:2017)
	at android.os.Handler.dispatchMessage(handler.java:107)
	at android.os.Looper.loop(looper.java:214)
	at android.app.ActivityThread.main(activitythread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(runtimeinit.java:492)
	at com.android.internal.os.ZygoteInit.main(zygoteinit.java:935)
Caused by: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
	at w6.a.<init>(sourcefile:10)
	at m8.b.<init>(Unknown source:0)
	at m8.c.a(Unknown source:16)
	at m8.a.a(Unknown source:9)
	at r8.c.d(Unknown source:12)
	at r8.b.<init>(Unknown source:21)
	at r8.c.<init>(Unknown source:0)
	at de.christinecoenen.code.zapp.app.livestream.ui.list.ChannelListFragment.L(Unknown source:9)
	at androidx.fragment.app.z0.e(Unknown source:65)
	at androidx.fragment.app.z0.k(Unknown source:150)
	at androidx.fragment.app.r0.z(Unknown source:1044)
	at androidx.fragment.app.r0.U(Unknown source:91)
	at androidx.fragment.app.r0.x(Unknown source:73)
	at androidx.fragment.app.r0.t(Unknown source:64)
	at androidx.fragment.app.w.L(Unknown source:51)
	at androidx.navigation.fragment.NavHostFragment.L(Unknown source:553)
	at androidx.fragment.app.z0.e(Unknown source:65)
	at androidx.fragment.app.z0.k(Unknown source:150)
	at androidx.fragment.app.r0.z(Unknown source:1044)
	at androidx.fragment.app.r0.U(Unknown source:91)
	at androidx.fragment.app.r0.y(Unknown source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(sourcefile:43)
	at androidx.fragment.app.e0.onCreateView(sourcefile:3)
	at androidx.fragment.app.z.onCreateView(sourcefile:4)
	at android.view.LayoutInflater.tryCreateView(layoutinflater.java:1069)
	at android.view.LayoutInflater.createViewFromTag(layoutinflater.java:997)
	at android.view.LayoutInflater.createViewFromTag(layoutinflater.java:961)
	at android.view.LayoutInflater.rInflate(layoutinflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(layoutinflater.java:1084)
	at android.view.LayoutInflater.rInflate(layoutinflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(layoutinflater.java:1084)
	at android.view.LayoutInflater.inflate(layoutinflater.java:682)
	at android.view.LayoutInflater.inflate(layoutinflater.java:534)
	at de.christinecoenen.code.zapp.app.main.MainActivity.onCreate(Unknown source:12)
	at android.app.Activity.performCreate(activity.java:7802)
	at android.app.Activity.performCreate(activity.java:7791)
	at android.app.Instrumentation.callActivityOnCreate(instrumentation.java:1300)
	at android.app.ActivityThread.performLaunchActivity(activitythread.java:3246)
	at android.app.ActivityThread.handleLaunchActivity(activitythread.java:3410)
	at android.app.servertransaction.LaunchActivityItem.execute(launchactivityitem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(transactionexecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(transactionexecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(activitythread.java:2017)
	at android.os.Handler.dispatchMessage(handler.java:107)
	at android.os.Looper.loop(looper.java:214)
	at android.app.ActivityThread.main(activitythread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(runtimeinit.java:492)
	at com.android.internal.os.ZygoteInit.main(zygoteinit.java:935)
```

My hardware and software:
Device: Nokia 6.1
OS: Android 10 Vanilla
App Version: 8.3.0

**Comment by cemrich** [comment]
Thanks for reporting. This was an issue with code shrinking for release builds only - this is why tests haven't catched it. This issue is fixed with bugfix version 8.3.1
