### ISSUE TITLE
[8.3.0] / [8.3.1] crashing on app startup

### ISSUE THREAD

**Issue by Kr1ss-XD** [mediathekview/zapp#373]
The `8.3.0` update seems to have incorporated a regression on my device (_Xiaomi Redmi Note 11pro 5G / Android 13 / MIUI Global 14.0.1.0_). As soon as I the app is being opened, it would crash.

This might be related to #371 and/or #372 - I haven't changed the channel order though, and `8.3.1` hasn't fixed that issue for me.

(**EDIT/** I should mention that after downgrading to `8.2.0` the app starts up fine and works as expected.)

<details>
<summary><b>[Crash log]</b></summary>

```
REPORT_ID=87467dab-0195-44c3-bcbb-8864fac93660
USER_EMAIL=
USER_COMMENT=
IS_SILENT=false
USER_CRASH_DATE=2023-07-25T14:44:48.528+02:00
APP_VERSION_NAME=8.3.0
APP_VERSION_CODE=66
ANDROID_VERSION=13
PHONE_MODEL=2201116SG
BRAND=Redmi
SHARED_PREFERENCES=default.pref_key_player_zoomed=false
 default.pref_ui_mode=default
 default.pref_detail_landscape=false
 default.pref_download_wifi_only=true
 default.pref_shortcuts=["zdf_info","ard_alpha","dreisat","arte"]
 default.pref_key_download_to_sd_card=true
 default.pref_key_stream_quality_cellular=medium
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{de.christinecoenen.code.zapp/de.christinecoenen.code.zapp.app.main.MainActivity}: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3909)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8410)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
 at w6.a.<init>(SourceFile:10)
 at m8.b.<init>(Unknown Source:0)
 at m8.c.a(Unknown Source:16)
 at m8.a.a(Unknown Source:9)
 at r8.c.d(Unknown Source:12)
 at r8.b.<init>(Unknown Source:21)
 at r8.c.<init>(Unknown Source:0)
 at de.christinecoenen.code.zapp.app.livestream.ui.list.ChannelListFragment.L(Unknown Source:9)
 at androidx.fragment.app.z0.e(Unknown Source:65)
 at androidx.fragment.app.z0.k(Unknown Source:150)
 at androidx.fragment.app.r0.z(Unknown Source:1044)
 at androidx.fragment.app.r0.U(Unknown Source:91)
 at androidx.fragment.app.r0.x(Unknown Source:73)
 at androidx.fragment.app.r0.t(Unknown Source:64)
 at androidx.fragment.app.w.L(Unknown Source:51)
 at androidx.navigation.fragment.NavHostFragment.L(Unknown Source:553)
 at androidx.fragment.app.z0.e(Unknown Source:65)
 at androidx.fragment.app.z0.k(Unknown Source:150)
 at androidx.fragment.app.r0.z(Unknown Source:1044)
 at androidx.fragment.app.r0.U(Unknown Source:91)
 at androidx.fragment.app.r0.y(Unknown Source:31)
 at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:43)
 at androidx.fragment.app.e0.onCreateView(SourceFile:3)
 at androidx.fragment.app.z.onCreateView(SourceFile:4)
 at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1098)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:1152)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
 at de.christinecoenen.code.zapp.app.main.MainActivity.onCreate(Unknown Source:12)
 at android.app.Activity.performCreate(Activity.java:8540)
 at android.app.Activity.performCreate(Activity.java:8504)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8410)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```
</details>

---

**PS:** _Thx a lot for sharing your work with us !_ 👍

**Comment by cemrich** [comment]
Thanks for your feedback!

8.3.0 should launch fine with unchanged channel list - this is why the crash passed quality control in the first place. I'll play around a bit with 8.3.1 and see if I can find anything. If not, crash reports should come in soon enough :)
