### ISSUE TITLE
Crash in sleep mode

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#440]
```
REPORT_ID=71a544d2-0f51-43d9-ad2d-592eea1c6b30
USER_EMAIL=
USER_COMMENT=
IS_SILENT=false
USER_CRASH_DATE=2024-07-21T09:07:19.015+02:00
APP_VERSION_NAME=8.5.2
APP_VERSION_CODE=72
ANDROID_VERSION=14
PHONE_MODEL=SM-A136B
BRAND=samsung
SHARED_PREFERENCES=default.pref_key_sleep_timer_delay_millis=3600000
default.pref_ui_mode=default
default.pref_detail_landscape=false
default.pref_key_language=de
default.pref_download_wifi_only=false
default.pref_shortcuts=[]
default.pref_key_start_tab=live
default.pref_key_player_zoomed=false
default.pref_enable_subtitles=false
default.dynamic_colors=false
default.acra.legacyAlreadyConvertedTo4.8.0=true
default.pref_key_pip_on_back=true
default.acra.legacyAlreadyConvertedToJson=true
default.pref_key_download_to_sd_card=true
default.acra.lastVersionNr=47
default.pref_key_stream_quality_cellular=lowest
STACK_TRACE=android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{301e223 u0 de.christinecoenen.code.zapp/androidx.work.impl.foreground.SystemForegroundService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8919)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

I usually send the crash report by e-mail as intended. For the sake of transparency, I am posting an example here.

**Comment by cemrich** [comment]
Thanks for the report! Can you please add a bit more context on when this crash did happen? This will help me reproduce it.

**Comment by WebworkrNet** [comment]
Describing is a difficult endeavour in this case. I start sleep mode and then fall asleep at some point. The next morning I see the crash message.

**Comment by WebworkrNet** [comment]
I usually set the sleep mode to 120 minutes.
However, the error does not always occur.
For example, a recent attempt to reproduce the phenomenon in personal wake mode with a shortened timer runtime has not yet been successful.

**Comment by WebworkrNet** [comment]
A crash may occur if the stream is interrupted by a fault in the Internet connection, although in my opinion there should be no logical dependency here.
