### ISSUE TITLE
Crash during background playback / bookmarking

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#449]
REPORT_ID=94108df4-a0f4-46d1-bfa4-8aa7acdf52db
USER_EMAIL=
USER_COMMENT=
IS_SILENT=false
USER_CRASH_DATE=2024-09-02T02:29:45.058+02:00
APP_VERSION_NAME=8.5.2
APP_VERSION_CODE=72
ANDROID_VERSION=14
PHONE_MODEL=SM-A136B
BRAND=samsung
SHARED_PREFERENCES=default.pref_key_sleep_timer_delay_millis=3600000
default.pref_ui_mode=default
default.pref_detail_landscape=false
default.pref_key_language=de
default.pref_download_wifi_only=false
default.pref_shortcuts=[]
default.pref_key_start_tab=live
default.pref_key_player_zoomed=false
default.pref_enable_subtitles=false
default.dynamic_colors=false
default.acra.legacyAlreadyConvertedTo4.8.0=true
default.pref_key_pip_on_back=true
default.acra.legacyAlreadyConvertedToJson=true
default.pref_key_download_to_sd_card=true
default.acra.lastVersionNr=47
default.pref_key_stream_quality_cellular=lowest
STACK_TRACE=java.lang.IllegalArgumentException: Navigation action/destination de.christinecoenen.code.zapp:id/to_mediathekDetailFragment cannot be found from the current destination g(de.christinecoenen.code.zapp:id/mediathekDetailFragment) label= class=de.christinecoenen.code.zapp.app.mediathek.ui.detail.MediathekDetailFragment
at B1.z.m(Unknown Source:130)
at B1.z.o(Unknown Source:9)
at de.christinecoenen.code.zapp.app.mediathek.ui.list.MediathekListFragment.f(Unknown Source:28)
at U2.n.onClick(Unknown Source:85)
at android.view.View.performClick(View.java:8047)
at android.view.View.performClickInternal(View.java:8024)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:31890)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8919)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by cemrich** [comment]
Deobfuscates stack trace:

```
java.lang.IllegalArgumentException: Navigation action/destination de.christinecoenen.code.zapp:id/to_mediathekDetailFragment cannot be found from the current destination g(de.christinecoenen.code.zapp:id/mediathekDetailFragment) label= class=de.christinecoenen.code.zapp.app.mediathek.ui.detail.MediathekDetailFragment
at androidx.navigation.NavController.navigate(Unknown Source:130)
                                     navigate
                                     navigate
at androidx.navigation.NavController.navigate(Unknown Source:9)
at de.christinecoenen.code.zapp.app.mediathek.ui.list.MediathekListFragment.onShowClicked(Unknown Source:28)
at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.de.christinecoenen.code.zapp.app.mediathek.ui.list.adapter.PagedMediathekShowListAdapter.createItemViewHolder$lambda$1(Unknown Source:85)
                                                                           onClick
at android.view.View.performClick(View.java:8047)
at android.view.View.performClickInternal(View.java:8024)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:31890)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8919)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by cemrich** [comment]
I think this crash might occur, when clicking multiple times on a mediathek show list item (very fast). 
However, I cannot reproduce this behaviour. Could you please test double clicking shows on your device and report back if Zapp crashes? That would be very helpful :)
