### ISSUE TITLE
First crash, then "my programs" empty

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#466]
**Steps to reproduce**
Playing a downloaded video

**Expected behaviour**

1. No crash
2. No data loss 

**Actual behaviour**

1. Crash
2. Afterwards, all content under "my programmes" (downloads, continue watching, bookmarks) disappeared.

Forcing the app to close via the settings and then restarting it in the expectation that the database entries would be available again after a reboot did not work. 
Restarting the device did not help either. The contents have still disappeared. 
The downloads themselves are still available. Nevertheless, the loss of the list of failed downloads, status of viewed videos and bookmarks is very annoying. I also occasionally use "continue viewing" as a list for resubmission.

**Are there any ways of restoring them?** Possibly via the Android backup? This is likely to show corresponding gaps in content with a time delay.

**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 14, One UI-Version 6.1**
**ZAPP**: 8.5.4 (74)

**Comment by WebworkrNet** [comment]
Zapp Crash Report 
(2 November 2024 12:11:33 CET, sent also by email)

```kotlin
Vielen Dank für die Rückmeldung!

Folgende Informationen helfen den Entwicklern von Zapp, den Fehler zu beheben:

REPORT_ID=cb3648df-cb15-40b0-a9f8-78cd312df4fb
USER_EMAIL=
USER_COMMENT=
IS_SILENT=false
USER_CRASH_DATE=2024-11-02T12:10:55.652+01:00
APP_VERSION_NAME=8.5.4
APP_VERSION_CODE=74
ANDROID_VERSION=14
PHONE_MODEL=SM-A136B
BRAND=samsung
SHARED_PREFERENCES=default.pref_key_sleep_timer_delay_millis=3600000
default.pref_ui_mode=default
default.pref_detail_landscape=false
default.pref_key_language=de
default.pref_download_wifi_only=false
default.pref_shortcuts=[]
default.pref_key_start_tab=live
default.pref_key_player_zoomed=false
default.pref_enable_subtitles=false
default.dynamic_colors=false
default.acra.legacyAlreadyConvertedTo4.8.0=true
default.pref_key_pip_on_back=true
default.acra.legacyAlreadyConvertedToJson=true
default.pref_key_download_to_sd_card=true
default.acra.lastVersionNr=47
default.pref_key_stream_quality_cellular=lowest
STACK_TRACE=android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11 SQLITE_CORRUPT[11])
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(sqliteconnection.java:1362)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(sqlitesession.java:838)
at android.database.sqlite.SQLiteQuery.fillWindow(sqlitequery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(sqlitecursor.java:157)
at android.database.sqlite.SQLiteCursor.getCount(sqlitecursor.java:144)
at [x4.h.call](https://x4.h.call/)(Unknown Source:1899)
at S1.b.q(Unknown Source:80)
at a5.a.o(Unknown Source:8)
at [y5.E.run](https://y5.e.run/)(Unknown Source:112)
at java.util.concurrent.ThreadPoolExecutor.runWorker(threadpoolexecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$[Worker.run](https://worker.run/)(threadpoolexecutor.java:644)
at [java.lang.Thread.run](https://java.lang.thread.run/)(thread.java:1012)
Suppressed: D5.g: [q0{Cancelling}@d7810d7, Dispatchers.Main.immediate]
```

**Comment by cemrich** [comment]
Thank you very much for reporting!

This is the first time this issue occurs - we received no other related crash reports via email. It looks like the sqlite database Zapp is using to store data has been corrupted and cannot be saved. Restoring an Android backup should bring back the data (when the backup has been configured correctly) - it is worth a try.

Is Zapp now running without crashes or still crashing when viewing a mediathek video?

This is the deobfuscated stack trace - but no useful information there:
```
android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11 SQLITE_CORRUPT[11])
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(sqliteconnection.java:1362)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(sqlitesession.java:838)
at android.database.sqlite.SQLiteQuery.fillWindow(sqlitequery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(sqlitecursor.java:157)
at android.database.sqlite.SQLiteCursor.getCount(sqlitecursor.java:144)
at [x4.h.call](https://x4.h.call/)(Unknown Source:1899)
at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(Unknown Source:80)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
at [y5.E.run](https://y5.e.run/)(Unknown Source:112)
at java.util.concurrent.ThreadPoolExecutor.runWorker(threadpoolexecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$[Worker.run](https://worker.run/)(threadpoolexecutor.java:644)
at [java.lang.Thread.run](https://java.lang.thread.run/)(thread.java:1012)
Suppressed: D5.g: [q0{Cancelling}@d7810d7, Dispatchers.Main.immediate]
```

**Comment by WebworkrNet** [comment]
1. How do I restore the last backup? Do I need to uninstall the app first and then reinstall it?

2. Should I test the playback of a downloaded video before or after the restore? I ask because of the risk of unintentional overwriting. If the test case were to be overwritten, this would of course not be so tragic.

**Comment by cemrich** [comment]
1. Sorry, I don't know your backup system.
2. Any backup on Android should override at least the database. So any changes you make now (maybe exclusing file downloads) should be reverted by your backup. When in doubt, please don't test anything and prioritize your data restoral.

**Comment by WebworkrNet** [comment]
Re 1) 
I use the native backup system of Android, as probably most users do. Gdrive (Google Drive) shows the available backups. The last backup is from November 2nd. However, the backed up data from ZAPP is from mid-October. This poses two problems: 

- a) I don't see any way to specifically restore only the data from this app. Correct me if I'm wrong. The only option is to reset the entire smartphone to factory settings and then start a complete restore. I don't think that's proportionate. "Shooting sparrows with cannons."

- b) The backed up app data is from October 13. Shouldn't they also be from November 2 (or close to that date) if I usually make changes to "my programs" almost daily?

![Screenshot_20241103_061806_Drive](https://github.com/user-attachments/assets/0689a5e9-ffd6-4182-a2f4-4bbc4f3a9513)

![Screenshot_20241103_061830_Drive](https://github.com/user-attachments/assets/ad106c64-b300-4a4f-98ef-572cc330c57f)

**Comment by WebworkrNet** [comment]
Functionality of the app after the crash:

1. All functions worked normally after the crash. 
2. After uninstalling and reinstalling the app, the database was empty again. The assumption that the data from the backup would be available was not fulfilled. I probably made the wrong assumptions at first. See also [previous comment](https://github.com/mediathekview/zapp/issues/466#issuecomment-2453406684).
After reinstalling at the time of activating the app notifications, the app initially crashed several times without generating an email report.

**Comment by cemrich** [comment]
1. Thank you very much for testing this!
2. I am sorry, but I cannot help you with backup / restore. Uninstalling and reinstalling *should* delete all data and no more crashes should occur.

**Comment by cemrich** [comment]
I will close this issue now. Feel free to open a new one if you experience further problems.
