### ISSUE TITLE
Open a show leads to crash

### ISSUE THREAD

**Issue by cintek** [mediathekview/zapp#468]
I downloaded a show and then when I tried to open another show the app crashed. A restart of the phone did help but not long after that I couldn't open a show again. This is the logcat:

```
11-25 11:43:28.852  9652  9862 E a       : ACRA caught a IllegalArgumentException for de.christinecoenen.code.zapp
11-25 11:43:28.852  9652  9862 E a       : java.lang.IllegalArgumentException: Primary directory Movies not allowed for content://media/2de1-c26f/file/1000009278; allowed directories are [Download, Documents]
11-25 11:43:28.852  9652  9862 E a       : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
11-25 11:43:28.852  9652  9862 E a       : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
11-25 11:43:28.852  9652  9862 E a       : 	at android.content.ContentProviderProxy.update(ContentProviderNative.java:653)
11-25 11:43:28.852  9652  9862 E a       : 	at android.content.ContentResolver.update(ContentResolver.java:2400)
11-25 11:43:28.852  9652  9862 E a       : 	at android.content.ContentResolver.update(ContentResolver.java:2362)
11-25 11:43:28.852  9652  9862 E a       : 	at c4.b.c(Unknown Source:77)
11-25 11:43:28.852  9652  9862 E a       : 	at c4.u.q(Unknown Source:398)
11-25 11:43:28.852  9652  9862 E a       : 	at a5.a.o(Unknown Source:8)
11-25 11:43:28.852  9652  9862 E a       : 	at y5.u0.z(Unknown Source:53)
11-25 11:43:28.852  9652  9862 E a       : 	at y5.a.o(Unknown Source:22)
11-25 11:43:28.852  9652  9862 E a       : 	at a5.a.o(Unknown Source:31)
11-25 11:43:28.852  9652  9862 E a       : 	at y5.E.run(Unknown Source:112)
11-25 11:43:28.852  9652  9862 E a       : 	at r3.q.run(Unknown Source:887)
11-25 11:43:28.852  9652  9862 E a       : 	at F5.k.run(Unknown Source:2)
11-25 11:43:28.852  9652  9862 E a       : 	at F5.a.run(Unknown Source:95)
11-25 11:43:28.852  9652  9862 E a       : 	Suppressed: D5.g: [q0{Cancelling}@990533, Dispatchers.IO]
```

I could solve the issue by clearing the data of the app in the Android settings ("Storage and cache" -> "Clear storage") but this might be interesting for you to prevent this issue. Sadly, I'm not able to reproduce the issue now. Before clearing the storage it happened always when opening a show.

Using Zapp 8.5.4 (74) from the F-droid store.

**Comment by nowhereSOURAV1708** [comment]
Because the program attempted to access the "Movies" folder—which Android only permits access to select directories like "Download" and "Documents"—it crashed. The error was brought on by this.

1. The first thing you can do is to make sure the app has the proper rights to access storage, particularly on Android 10 and later.
2. Use Allowed Folders: Only folders like "Download" or "Documents" should be accessible by the application. To adhere to this regulation, it must be corrected.
3. Clear Data: The problem may have been caused by corrupted data, as clearing the app's data (Settings > Storage > Clear Data) helps. However, this is a short-term solution.
4. Update the App: Verify whether an updated version of the app is accessible, as this bug may be resolved in a future release.

**Comment by cintek** [comment]
Since the report I didn't experience this problem anymore. Maybe because of a newer Android (iode OS) version or maybe something else.
